# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: EmptyRepo
      type: github
      endpoint: dmitrykurmanov:admin
      name: surveyjs/azure-pipelines-repo-dont-remove-please

trigger:
  batch: true
  branches:
    exclude:
    - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: 'windows-latest'

jobs:

- job: CreatorV2Core
  steps:
  - checkout: self
  - checkout: EmptyRepo
    persistCredentials: true
    clean: true

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/"
      Contents: "package.json"
      TargetFolder: "$(Build.SourcesDirectory)/Temp/"
      OverWrite: true
    displayName: "Copy package.json for cache key"

  - task: Cache@2
    inputs:
      key: 'npm-cache-creator-core | $(Build.SourcesDirectory)/Temp/package.json'
      path: $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/node_modules
      cacheHitVar: NPM_CACHE_RESTORED
    displayName: Cache NPM Core

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '56'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
      OverWrite: true

  - task: Npm@1
    displayName: 'Npm install survey-creator-core'
    inputs:
      command: install
      verbose: false
      workingDir: $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
    condition: ne(variables.NPM_CACHE_RESTORED, 'true')

  # update 'file' npm dependencies in case of cache
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/survey-library/build/survey-core
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/node_modules/survey-core'
      OverWrite: true
    condition: ne(variables.NPM_CACHE_RESTORED, 'false')
    displayName: 'copy survey-core in case of npm cache'
  # EO update 'file' npm dependencies in case of cache

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run remove-package-lock
    displayName: 'npm run remove-package-lock'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run build:i18n
    displayName: 'Build Creator V2 Core i18n'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core
      npm run build
    displayName: 'Build Creator V2 Core'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/build'
      targetFolder: $(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-core

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/SurveyJSCreatorV2Build/build/survey-creator-core'
      ArtifactName: 'SurveyJSCreatorV2Build-VRT-Core-$(Build.BuildId)'
      publishLocation: 'Container'  


# ======================= CreatorV2Knockout ======================= #
- job: CreatorV2Knockout
  dependsOn: CreatorV2Core
  steps:
  - checkout: self
  - checkout: EmptyRepo
    persistCredentials: true
    clean: true

  - task: PowerShell@2
    displayName: 'update Google Chrome to latest'
    inputs:
      targetType: 'inline'
      script: '$Path = $env:TEMP; $Installer = ''chrome_installer.exe''; Invoke-WebRequest -Uri ''http://dl.google.com/chrome/install/375.126/chrome_installer.exe'' -OutFile $Path\$Installer; Start-Process -FilePath $Path\$Installer -Args ''/silent /install'' -Verb RunAs -Wait; Remove-Item -Path $Path\$Installer'

  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/"
      Contents: "package.json"
      TargetFolder: "$(Build.SourcesDirectory)/Temp/"
      OverWrite: true
    displayName: "Copy package.json for cache key"

  - task: Cache@2
    inputs:
      key: 'npm-cache-creator-knockout | $(Build.SourcesDirectory)/Temp/package.json'
      path: $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules
      cacheHitVar: NPM_CACHE_RESTORED
    displayName: Cache NPM

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'specific'
      project: 'af2804d2-859a-4705-9ef5-cdf46d1d5d4f'
      pipeline: '56'
      specificBuildWithTriggering: true
      buildVersionToDownload: 'latest'
      downloadType: 'single'
      artifactName: 'SurveyJSLibraryBuild'
      downloadPath: '$(System.ArtifactsDirectory)'
  
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'SurveyJSCreatorV2Build-VRT-Core-$(Build.BuildId)'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-library/build'
      OverWrite: true
  
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(System.ArtifactsDirectory)/SurveyJSCreatorV2Build-VRT-Core-$(Build.BuildId)
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-core/build'
  
  - script: |
      cd $(Build.SourcesDirectory)/survey-creator
      npm install devextreme-screenshot-comparer -D
    displayName: 'install devextreme-screenshot-comparer to root'

  - task: Npm@1
    displayName: 'Npm install survey-creator-knockout'
    inputs:
      command: install
      verbose: false
      workingDir: $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
    condition: ne(variables.NPM_CACHE_RESTORED, 'true')

  # update 'file' npm dependencies in case of cache
  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/survey-library/build/survey-core
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-core'
      OverWrite: true
    condition: ne(variables.NPM_CACHE_RESTORED, 'false')
    displayName: 'copy survey-core in case of npm cache'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/survey-library/build/survey-knockout-ui
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-knockout-ui'
      OverWrite: true
    condition: ne(variables.NPM_CACHE_RESTORED, 'false')
    displayName: 'copy survey-knockout-ui in case of npm cache'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(System.ArtifactsDirectory)/SurveyJSCreatorV2Build-VRT-Core-$(Build.BuildId)
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-creator-core'
      OverWrite: true
    condition: ne(variables.NPM_CACHE_RESTORED, 'false')
    displayName: 'copy survey-creator-core in case of npm cache'
  # EO update 'file' npm dependencies in case of cache


  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm run remove-package-lock
    displayName: 'npm run remove-package-lock'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-core'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-core'
      OverWrite: true
    displayName: 'copy build from library for f-f tests'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/build/survey-knockout-ui'
      Contents: '**'
      TargetFolder: '$(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout/node_modules/survey-knockout-ui'
      OverWrite: true
    displayName: 'copy build from library for f-f tests'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm run build
    displayName: 'Build CreatorV2 Knockout'

  - script: |
      cd $(Build.SourcesDirectory)/survey-creator/packages/survey-creator-knockout
      npm run visual-regression-tests:ci
    displayName: 'Visual Regression Tests CreatorV2 Knockout'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/survey-creator/visualRegressionTests'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Creator_KO_VRT'
      OverWrite: true
    condition: always()
    displayName: 'copy vrt ko artifacts'
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/Creator_KO_VRT/'
      ArtifactName: 'Creator_KO_VRT'
      publishLocation: 'Container'
    condition: always()
    displayName: 'publish vrt ko artifacts'

